version: '3'
services:
    my_jenkins:
        container_name: jenkins
        image: jenkins
        ports:
            - "8080:8080"
        volumes:
            - "$PWD/jenkins-data:/var/jenkins_home"
        networks:
            - net
networks:
    net:  
