version: '3'
services:
    my_jenkins:
        container_name: jenkins
        image: jenkins/jenkins
        ports:
            - "8080:8080"
        volumes:
            - "$PWD/jenkins-data:/var/jenkins_home"
        networks:
            - net
    my_centos:
        container_name: centos
        image: mycentos
        build:
            context: centos7
        networks:
            - net
    db_host:
        container_name: db 
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=mysql1234"
        volumes:
            - "$PWD/mysql_data:/var/lib/mysql"
        networks:
            - net
networks:
    net:  
